name: liquid
description: Parser from the Liquid Template Engine to the Widgets
version: 1.0.0
homepage: none
publish_to: none

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: '>=3.7.8'

dependencies:
  flutter:
    sdk: flutter
  liquid_parser:
    path: ../liquid_parser

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lint:
    path: ../lint

flutter: