name: analytics
description: A new Flutter package project.
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.0-42.0.dev <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  config:
    path: ../config
  tools:
    path: ../tools
  amplitude_flutter: ^3.14.0
  go_router: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  lint:
    path: ../lint

flutter: