name: analytics
description: A new Flutter package project.
version: 1.0.0
homepage: nope
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  config:
    path: ../config
  tools:
    path: ../tools
  amplitude_flutter: ^3.14.0
  vrouter: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  lint:
    path: ../lint

flutter: