name: analytics
description: A new Flutter package project.
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_configuration:
    path: ../nanc_configuration
  nanc_tools:
    path: ../nanc_tools
  amplitude_flutter: ^3.14.0
  go_router: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../nanc_lints

flutter: