name: markdown_code_push_core
description: This package add you ability to easily create any md-tags and convert them into the widgets
version: 1.0.0
verified publisher:
  - alphamikle@gmail.com
homepage: TODO
publish_to: none

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: '>=3.7.8'

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  markdown: ^6.0.1
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  flutter_markdown: ^0.6.13+1
  html: ^0.15.1
  collection: ^1.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
