name: model
description: A new Flutter package project.
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.0-42.0.dev <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  fields:
    path: ../fields
  icons:
    path: ../icons
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  autoequal: ^0.5.1

dev_dependencies:
  lint:
    path: ../lint
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  autoequal_gen: ^0.5.1

flutter: