name: markdown_code_push
description: A rich markdown renderer with custom elements
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0-201.0.dev <4.0.0'
  flutter: '>=3.8.0-4.0.pre.9'

dependencies:
  flutter:
    sdk: flutter
  markdown_code_push_core:
    path: ../markdown_code_push_core
  tools:
    path: ../tools
  rich_renderer:
    path: ../rich_renderer
  markdown: ^6.0.1
  xml2json: ^5.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: