name: nanc_fonts
description: Fonts package for Nanc
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../nanc_lints

flutter: