name: nanc_monorepo
description: Nanc monorepo
version: 1.0.0
verified publisher:
  - alphamikle@gmail.com
homepage: client.nanc.io

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  args: ^2.3.2
  path: ^1.8.2
  flutter_lints: ^2.0.1
  recase: ^4.1.0
  nanc_lints:
    path: ./nanc_lints

flutter:
