name: flutter_admin_monorepo
description: This package add you ability to easily create any md-tags and convert them into the widgets
version: 1.0.0
verified publisher:
  - alphamikle@gmail.com
homepage: client.nanc.io

environment:
  sdk: '>=3.0.0-201.0.dev <4.0.0'
  flutter: '>=3.8.0-4.0.pre.9'

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  args: ^2.3.2
  path: ^1.8.3
  flutter_lints: ^2.0.1
  lint:
    path: ./lint

flutter:
