bash build.sh ./additions
bash build.sh ./cms
bash build.sh ./code_text_field
bash build.sh ./components
bash build.sh ./config
bash build.sh ./fields
bash build.sh ./file_syncer
bash build.sh ./fonts
bash build.sh ./icons
bash build.sh ./markdown_code_push
bash build.sh ./markdown_code_push_core
bash build.sh ./model
bash build.sh ./nanc_backend
bash build.sh ./nanc_client
bash build.sh ./nanc_webrtc
bash build.sh ./rich_renderer
bash build.sh ./storybook
bash build.sh ./tools
bash build.sh ./ui_kit