name: fields
description: A new Flutter package project.
version: 0.0.1
homepage: nope
publish_to: none

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: '>=3.7.8'

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  model:
    path: ../model
  ui_kit:
    path: ../ui_kit
  cms:
    path: ../cms
  icons:
    path: ../icons
  config:
    path: ../config
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  copy_with_extension: ^5.0.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  vrouter: ^1.2.1
  autoequal: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
    path: ../lint
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.0
  build_runner: ^2.3.3
  autoequal_gen: ^0.5.1
  flutter_lints: ^2.0.1

flutter: