name: fields
description: A new Flutter package project.
version: 0.0.1
homepage: nope
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  model:
    path: ../model
  ui_kit:
    path: ../ui_kit
  cms:
    path: ../cms
  icons:
    path: ../icons
  config:
    path: ../config
  nanc_config:
    path: ../nanc_config
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  vrouter: ^1.2.1
  autoequal: ^0.5.1

dev_dependencies:
  lint:
    path: ../lint
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  autoequal_gen: ^0.5.1
  flutter_lints: ^2.0.1

flutter: