name: fields
description: The field is an arterial Nanc. The fields are responsible for how you will edit the data, what data you will edit, and where you will edit the data.
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  model:
    path: ../model
  ui_kit:
    path: ../ui_kit
  cms:
    path: ../cms
  icons:
    path: ../icons
  config:
    path: ../config
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  autoequal: ^0.5.1

dev_dependencies:
  lint:
    path: ../lint
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  autoequal_gen: ^0.5.1
  flutter_lints: ^2.0.1

flutter: