name: nanc_backend
description: NANC project backend demo
publish_to: 'none'
version: 1.0.0+25

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  cms:
    path: ../cms
  nanc_webrtc:
    path: ../nanc_webrtc
  tools:
    path: ../tools
  model:
    path: ../model
  fields:
    path: ../fields
  ui_kit:
    path: ../ui_kit
  icons:
    path: ../icons
  animation_debugger:
    path: ../../../3_open_source_projects/animation_debugger
  components:
    path: ../components
  additions:
    path: ../additions
  analytics:
    path: ../analytics
  fonts:
    path: ../fonts
  nanc_config:
    path: ../nanc_config
  cupertino_icons: ^1.0.5
  pretty_qr_code: ^2.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  path_provider: ^2.0.15
  path: ^1.8.3
  autoequal: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  autoequal_gen: ^0.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Blazeface
      fonts:
        - asset: assets/fonts/blazeface.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
          weight: 400
        - asset: assets/fonts/helvetica_light.ttf
          weight: 300
        - asset: assets/fonts/helvetica_bold.ttf
          weight: 500
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helvetica_neue_wide.ttf
          weight: 400
        - asset: assets/fonts/helvetica_neue_light.ttf
          weight: 300

# flutter pub run flutter_launcher_icons
flutter_icons:
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
  macos:
    generate: true
    image_path: "assets/logo.png"