name: icons
description: The icon pack for the NANC CMS
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  material_design_icons_flutter: ^6.0.7096
  fluentui_system_icons: ^1.1.201
  remixicon: ^1.0.0
  flutter_boxicons: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  path: ^1.8.3
  basic_utils: ^5.5.4
  args: ^2.4.1

flutter:
  assets:
    - assets/
    - assets/sicons/