name: nanc_api_firebase
description: Firebase API Implementation for Nanc
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_configuration: ^0.0.1
  nanc_tools: ^0.0.2
  nanc:
    path: ../nanc
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  autoequal: ^0.9.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../nanc_lints
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  autoequal_gen: ^0.9.1

flutter: