name: nanc_api_firebase
description: Firebase API Implementation for Nanc
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_configuration: ^0.0.3
  nanc_tools: ^0.0.3
  nanc: ^0.0.4
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  copy_with_extension: ^5.0.4
  equatable_annotations: ^1.0.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  json_serializable: ^6.9.5
  copy_with_extension_gen: ^5.0.4
  build_runner: ^2.4.15
  equatable_gen: ^1.0.4

flutter:
dependency_overrides:
  analyzer: ^6.0.0
