name: file_syncer
description: Package for syncing code editor with the file system
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.3.1
  js: ^0.6.7

dev_dependencies:
  flutter_lints: ^2.0.1
  lint:
    path: ../lint

flutter: