name: nanc_configuration
description: Nanc CMS configuration
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.3

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_tools: ^0.0.3
  nanc_fonts: ^0.0.1
  copy_with_extension: ^6.0.1
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  equatable_annotations: ^1.0.1
  autoequal: ^0.9.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  json_serializable: ^6.9.5
  copy_with_extension_gen: ^6.0.1
  build_runner: ^2.4.15
  equatable_gen: ^1.0.4
  autoequal_gen: ^0.9.5
dependency_overrides:
  analyzer: ^6.0.0
