name: nanc_configuration
description: Nanc CMS configuration
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.3

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_tools: ^0.0.3
  nanc_fonts: ^0.0.1
  copy_with_extension: ^5.0.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  autoequal: ^0.9.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  autoequal_gen: ^0.9.1