name: nanc_api_local
description: Local API for Nanc, based on LocalStorage or local JSON file
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 1.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_tools: ^0.0.3
  nanc: ^0.0.4
  nanc_configuration: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0

flutter:
dependency_overrides:
  analyzer: ^7.0.0
