name: nanc_api_local
description: Local API for Nanc, based on LocalStorage or local JSON file
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../../nanc/tools
  fields:
    path: ../../nanc/fields
  model:
    path: ../../nanc/model
  config:
    path: ../../nanc/config

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
    path: ../lint
  flutter_lints: ^2.0.1

flutter: