name: nanc_webrtc
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  dio: ^4.0.6
  json_annotation: ^4.8.0
  copy_with_extension: ^5.0.0
  peerdart: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.0

flutter: