name: nanc_webrtc
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  dio: ^5.1.2
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  peerdart: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  copy_with_extension_gen: ^5.0.2

flutter: