enum FieldType {
  custom,
  field,
  dateField,
  enumField,
  iconField,
  idField,
  stringField,
  multiSelectorField,
  numberField,
  selectorField,
  boolField,
  dynamicField,
  structuredField,
  structureField,
  colorField,
  screenField,
  headerField,
  // TODO(alphamikle): Add new field types here
}
