name: nui_svg_renderer
description: SVG Renderer Package for the Nui - Nanc Server Driven UI
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nui: ^0.0.2
  nanc_tools: ^0.0.2
  nanc_icons: ^0.0.1
  flutter_svg: ^2.0.7
  vector_graphics: ^1.1.7
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4

flutter: