name: nanc_svg_renderer
description: SVG Renderer Package for the Nanc
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nui:
    path: ../nui
  nanc_tools:
    path: ../nanc_tools
  nanc_icons:
    path: ../nanc_icons
  flutter_svg: ^2.0.7
  vector_graphics: ^1.1.7
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../nanc_lints
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4

flutter: