name: cms
description: NANC - Next-Gen Backend-agnostic CMS
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: '>=3.7.8'

dependencies:
  flutter:
    sdk: flutter
  nanc_renderer:
    path: ../nanc_renderer
  markdown_code_push_core:
    path: ../markdown_code_push_core
  code_text_field:
    path: ../code_text_field
  tools:
    path: ../tools
  fields:
    path: ../fields
  model:
    path: ../model
  ui_kit:
    path: ../ui_kit
  config:
    path: ../config
  animation_debugger:
    path: ../../../3_open_source_projects/animation_debugger
  file_syncer:
    path: ../file_syncer
  icons:
    path: ../icons
  additions:
    path: ../additions
  analytics:
    path: ../analytics
  fonts:
    path: ../fonts
  cupertino_icons: ^1.0.5
  device_frame: ^1.1.0
  markdown: ^6.0.1
  vrouter: ^1.2.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  copy_with_extension: ^5.0.0
  bot_toast: ^4.0.3
  ulid: ^2.0.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  collection: ^1.17.0
  mask_text_input_formatter: ^2.4.0
  animations: ^2.0.7
  rive: ^0.10.1
  lottie: ^2.2.0
  flutter_markdown: ^0.6.13+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.0
  build_runner: ^2.3.3
  path: ^1.8.2
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  fonts:
    - family: BluePrintNonCommercial
      fonts:
        - asset: assets/fonts/blueprint_font_non_commercial.ttf

  assets:
    - assets/
    - assets/animations/
    - assets/fonts/

# flutter pub run flutter_launcher_icons
flutter_icons:
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
  macos:
    generate: true
    image_path: "assets/logo.png"
