name: config
description: NANC project config
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lint:
    path: ../lint

flutter:
  uses-material-design: true