name: nui_converter
description: "Converter from XML to JSON or gRPC for tags"
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  protobuf: ^4.1.0
  proto_annotations: ^5.0.0
  equatable: ^2.0.7
  equatable_annotations: ^1.0.1
  xml: ^6.5.0
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.26.2
  nanc_lints: ^1.0.0
  json_serializable: ^6.9.5
  copy_with_extension_gen: ^6.0.1
  build_runner: ^2.4.15
  equatable_gen: ^1.0.4
  proto_generator: ^5.0.0

dependency_overrides:
  analyzer: ^6.0.0

executables:
  ncov: convert
