name: nanc
description: Nanc - Not a normal, next-gen backend-agnostic CMS
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_renderer:
    path: ../nanc_renderer
  nanc_code_text_field:
    path: ../nanc_code_text_field
  tools:
    path: ../tools
  nanc_configuration:
    path: ../nanc_configuration
  nanc_icons:
    path: ../nanc_icons
  analytics:
    path: ../analytics
  nanc_fonts:
    path: ../nanc_fonts
  animation_debugger: ^1.0.0
  cupertino_icons: ^1.0.5
  device_frame: ^1.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  ulid: ^2.0.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  collection: ^1.17.1 # no updates because of flutter
  mask_text_input_formatter: ^2.4.0
  animations: ^2.0.7
  rive: ^0.11.1
  lottie: ^2.3.2
  flutter_markdown: ^0.6.14
  copy_with_extension: ^5.0.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  autoequal: ^0.9.1
  go_router: ^8.0.3
  stack_trace: ^1.11.0
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^4.4.0
  dropdown_search: ^5.0.6
  flex_color_scheme: ^7.3.1
  shimmer: ^3.0.0
  linked_scroll_controller: ^0.2.0
  loading_animation_widget: ^1.2.0+4
  super_sliver_list: ^0.2.1
  google_fonts: any
  file_picker: ^5.3.1
  js: ^0.6.7

dev_dependencies:
  nanc_lints:
    path: ../nanc_lints
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  autoequal_gen: ^0.9.1
  path: ^1.8.3

flutter:
  uses-material-design: true
  fonts:
    - family: BluePrintNonCommercial
      fonts:
        - asset: assets/fonts/blueprint_font_non_commercial.ttf

  assets:
    - assets/
    - assets/animations/
    - assets/fonts/
    - assets/images/