name: nui
description: Server Driven UI Engine and the part of Nanc CMS
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.3

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_tools: ^0.0.2
  nanc_icons: ^0.0.1
  nanc_fonts: ^0.0.1
  nanc_configuration: ^0.0.1
  nui_converter: ^0.0.1
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  cached_network_image: ^3.3.1
  flutter_blurhash: ^0.8.2
  xml: ^6.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  eval_ex: ^1.1.8
  decimal: ^2.3.3
  proto_annotations: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.4
  build_runner: ^2.4.8
  proto_generator: ^4.3.0

flutter: