name: nanc_demo_cms
description: Demo Nanc CMS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  cms:
    path: ../cms
  nanc_api_supabase:
    path: ../nanc_api_supabase
  nanc_api_firebase:
    path: ../nanc_api_firebase
  nanc_config:
    path: ../nanc_config
  icons:
    path: ../icons
  fields:
    path: ../fields
  model:
    path: ../model

dev_dependencies:
  flutter_lints: ^2.0.1
  lint:
    path: ../lint

flutter:
  uses-material-design: true