name: nanc_lints
description: A set of rules for the Nanc CMS
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
dependency_overrides:
  analyzer: ^7.0.0
