include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
# https://dart-lang.github.io/linter/lints/index.html

analyzer:
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false
  errors:
    todo: warning
    missing_return: error
    always_use_package_imports: error
    division_optimization: error
    must_call_super: error
    always_put_required_named_parameters_first: warning
    unnecessary_await_in_return: error
    invalid_use_of_protected_member: error
    sort_constructors_first: warning
    sort_unnamed_constructors_first: warning
    use_super_parameters: warning
  exclude:
    - "**.g.dart"

linter:
  rules:
    # CUSTOM RULES
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    omit_local_variable_types: false
    unnecessary_await_in_return: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_super_parameters: true
    always_declare_return_types: true
    use_enums: true
    unawaited_futures: true
    cancel_subscriptions: true
    close_sinks: true
    discarded_futures: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_redundant_argument_values: true
    avoid_void_async: true
    directives_ordering: true
    flutter_style_todos: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    package_api_docs: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_int_literals: true
    use_colored_box: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true # EXPERIMENTAL
    use_named_constants: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true


    # OVERRIDDEN RULES FROM FLUTTER LINTS
    # https://github.com/flutter/packages/blob/main/packages/flutter_lints/lib/flutter.yaml


    # RULES FROM LINTS:RECOMMENDED
    # https://github.com/dart-lang/lints/blob/main/lib/recommended.yaml
    package_names: false


    # RULES FROM LINTS:CORE
    # https://github.com/dart-lang/lints/blob/main/lib/core.yaml

