name: additions
description: Additional things for NANC-CMS and NANC-Based apps
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  nanc_renderer:
    path: ../nanc_renderer
  icons:
    path: ../icons
  ui_kit:
    path: ../ui_kit
  flutter:
    sdk: flutter
  analytics:
    path: ../analytics
  nanc_config:
    path: ../nanc_config
  url_launcher: ^6.1.11
  share_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
