name: additions
description: Additional things for NANC-CMS and NANC-Based apps
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  rich_renderer:
    path: ../rich_renderer
  flutter:
    sdk: flutter
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
