name: additions
description: Additional things for NANC-CMS and NANC-Based apps
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: '>=3.7.8'

dependencies:
  nanc_renderer:
    path: ../nanc_renderer
  icons:
    path: ../icons
  ui_kit:
    path: ../ui_kit
  flutter:
    sdk: flutter
  analytics:
    path: ../analytics
  url_launcher: ^6.1.8
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
