name: nanc_icons
description: The icon pack for the Nanc CMS
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  material_design_icons_flutter: ^7.0.7296
  fluentui_system_icons: ^1.1.205
  remixicon: ^1.0.0
  flutter_boxicons: ^3.0.0

dev_dependencies:
  nanc_lints:
    path: ../nanc_lints
  path: ^1.8.3
  basic_utils: ^5.5.4
  args: ^2.4.1

flutter:
  assets:
    - assets/
    - assets/sicons/