name: tools
description: Tools for all modules
version: 0.0.1
homepage: -_-
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  config:
    path: ../config
  markdown: ^6.0.0
  collection: ^1.16.0
  material_design_icons_flutter: ^6.0.7096
  fluentui_system_icons: ^1.1.184
  flutter_boxicons: ^3.0.0
  super_clipboard: ^0.1.6
  html: ^0.15.1
  archive: ^3.3.4
  ulid: ^2.0.0
  basic_utils: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt:
    git:
      url: git@github.com:leocavalcante/encrypt.git
      ref: 235ca6fa9f10c981bb20340362d97b89893087de # The commit with the [collection] package, compatible with the CMS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: