name: tools
description: Tools for all modules
version: 0.0.1
homepage: -_-
publish_to: none

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: '>=3.7.8'

dependencies:
  flutter:
    sdk: flutter
  config:
    path: ../config
  markdown: ^6.0.1
  collection: ^1.17.0
  material_design_icons_flutter: ^6.0.7096
  fluentui_system_icons: ^1.1.190
  flutter_boxicons: ^3.0.0
  html: ^0.15.1
  archive: ^3.3.6
  ulid: ^2.0.0
  basic_utils: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^3.0.3
  path_provider: ^2.0.12
  url_launcher: ^6.1.8
  encrypt: ^5.0.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  lint:
    path: ../lint

flutter: