name: nanc_analytics
description: Analytics for the Nanc CMS
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_configuration: ^0.0.3
  nanc_tools: ^0.0.3
  amplitude_flutter: ^3.16.2
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0

flutter: