name: nanc_client
description: NANC project demo client
publish_to: 'none'
version: 1.0.0+33

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: '>=3.7.8'

dependencies:
  flutter:
    sdk: flutter
  nanc_webrtc:
    path: ../nanc_webrtc
  tools:
    path: ../tools
  cms:
    path: ../cms
  nanc_renderer:
    path: ../nanc_renderer
  ui_kit:
    path: ../ui_kit
  icons:
    path: ../icons
  additions:
    path: ../additions
  components:
    path: ../components
  analytics:
    path: ../analytics
  cupertino_icons: ^1.0.5
  fonts:
    path: ../fonts
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  copy_with_extension: ^5.0.2
  vrouter: ^1.2.1
  device_frame: ^1.1.0
  mobile_scanner: ^3.1.0
  dio: ^4.0.6

#dependency_overrides:
#  mobile_scanner:
#    git:
#      url: https://github.com/juliansteenbakker/mobile_scanner
#      ref: bug/fix-macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Blazeface
      fonts:
        - asset: assets/fonts/blazeface.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica.ttf
          weight: 400
        - asset: assets/fonts/helvetica_light.ttf
          weight: 300
        - asset: assets/fonts/helvetica_bold.ttf
          weight: 500
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/helvetica_neue_wide.ttf
          weight: 400
        - asset: assets/fonts/helvetica_neue_light.ttf
          weight: 300

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo_v3.png"
  adaptive_icon_background: "#3A2623"
  adaptive_icon_foreground: "assets/logo_v3.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#5856E9"
    theme_color: "#5856E9"
  macos:
    generate: true
    image_path: "assets/logo_v3.png"