name: nanc_client
description: NANC project demo client
publish_to: 'none'
version: 1.0.0+28

environment:
  sdk: '>=3.0.0-201.0.dev <4.0.0'
  flutter: '>=3.8.0-4.0.pre.9'

dependencies:
  flutter:
    sdk: flutter
  nanc_webrtc:
    path: ../nanc_webrtc
  tools:
    path: ../tools
  cms:
    path: ../cms
  rich_renderer:
    path: ../rich_renderer
  markdown_code_push:
    path: ../markdown_code_push
  ui_kit:
    path: ../ui_kit
  icons:
    path: ../icons
  additions:
    path: ../additions
  components:
    path: ../components
  analytics:
    path: ../analytics
  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  copy_with_extension: ^5.0.0
  vrouter: ^1.2.1
  device_frame: ^1.1.0
  mobile_scanner: ^2.1.0
  dio: ^4.0.6

dependency_overrides:
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner
      ref: bug/fix-macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/

# flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo_v3.png"
  adaptive_icon_background: "#3A2623"
  adaptive_icon_foreground: "assets/logo_v3.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#5856E9"
    theme_color: "#5856E9"
  macos:
    generate: true
    image_path: "assets/logo_v3.png"