name: nanc_tools
description: nanc_tools for all Nanc modules
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.3

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  html: ^0.15.6
  archive: ^4.0.7
  ulid: ^2.0.1
  basic_utils: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  encrypt: ^5.0.3
  provider: ^6.1.5
  go_router: ^15.1.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0

flutter: