name: nanc_tools
description: nanc_tools for all Nanc modules
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.1 # no update because of flutter
  html: ^0.15.3
  archive: ^3.3.7
  ulid: ^2.0.0
  basic_utils: ^5.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^4.0.1
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  encrypt: ^5.0.1
  provider: ^6.0.5
  go_router: ^8.0.3
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints:
    path: ../nanc_lints

flutter: