name: nanc_renderer
description: Nanc XML Renderer
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  nanc_icons:
    path: ../nanc_icons
  nanc_fonts:
    path: ../nanc_fonts
  nanc_configuration:
    path: ../nanc_configuration
  tag_converter:
    path: ../tag_converter
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  cached_network_image: ^3.3.1
  flutter_blurhash: ^0.8.2
  xml: ^6.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  eval_ex: ^1.1.8
  decimal: ^2.3.3
  proto_annotations: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^5.0.4
  build_runner: ^2.4.8
  proto_generator: ^4.3.0

flutter: