name: nanc_config
description: Set of config interfaces and APIs for Nanc
version: 1.0.0
homepage: nope
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  model:
    path: ../model
  fields:
    path: ../fields
  nanc_renderer:
    path: ../nanc_renderer
  fonts:
    path: ../fonts
  copy_with_extension: ^5.0.0
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  autoequal: ^0.5.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
    path: ../lint
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.0
  build_runner: ^2.3.3
  autoequal_gen: ^0.5.1

flutter: