name: local_notifications
description: Notifications for Nanc
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ../ui_kit
  tools:
    path: ../tools

dev_dependencies:
  lint:
    path: ../lint
  flutter_lints: ^2.0.1