name: rich_renderer
description: Rich renderer module
version: 0.0.1
homepage: -_-
publish_to: none

environment:
  sdk: '>=3.0.0-201.0.dev <4.0.0'
  flutter: '>=3.8.0-4.0.pre.9'

dependencies:
  flutter:
    sdk: flutter
  markdown_code_push_core:
    path: ../markdown_code_push_core
  tools:
    path: ../tools
  icons:
    path: ../icons
  fonts:
    path: ../fonts
  markdown: ^6.0.1
  json_annotation: ^4.8.0
  copy_with_extension: ^5.0.0
  cached_network_image: ^3.2.3
  flutter_highlight2: ^0.8.3
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  lint:
    path: ../lint
  json_serializable: ^6.6.1
  copy_with_extension_gen: ^5.0.0
  build_runner: ^2.3.3

flutter: