name: rich_renderer
description: Rich renderer module
version: 0.0.1
homepage: -_-
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  markdown_code_push_core:
    path: ../markdown_code_push_core
  tools:
    path: ../tools
  icons:
    path: ../icons
  markdown: ^6.0.0
  json_annotation: ^4.7.0
  copy_with_extension: ^4.0.3
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.2
  flutter_highlight2: ^0.8.3
  flutter_blurhash: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.4.1
  copy_with_extension_gen: ^4.0.3
  build_runner: ^2.2.1

flutter: