name: ui_kit
description: The UI KIT for the NANC project
version: 1.0.0
homepage: nope
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.1"

dependencies:
  flutter:
    sdk: flutter
  tools:
    path: ../tools
  fields:
    path: ../fields
  model:
    path: ../model
  cms:
    path: ../cms
  icons:
    path: ../icons
  fonts:
    path: ../fonts
  code_text_field:
    path: ../code_text_field
  nanc_config:
    path: ../nanc_config
  flutter_typeahead: ^4.4.0
  dropdown_search: ^5.0.6
  animations: ^2.0.7
  mask_text_input_formatter: ^2.4.0
  vrouter: ^1.2.1
  flex_color_scheme: ^7.1.2
  shimmer: ^3.0.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  linked_scroll_controller: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  lint:
    path: ../lint

flutter: