name: nanc_api_supabase
description: Supabase API Implementation for Nanc
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 1.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.9"

dependencies:
  flutter:
    sdk: flutter
  nanc_configuration: ^0.0.3
  nanc: ^0.0.4
  nanc_tools: ^0.0.3
  supabase_flutter: ^2.9.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1
  equatable_annotations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0
  json_serializable: ^6.9.5
  copy_with_extension_gen: ^6.0.1
  build_runner: ^2.4.15
  equatable_gen: ^1.0.4
dependency_overrides:
  analyzer: ^7.0.0
