name: nanc_api_supabase
description: Supabase API Implementation for Nanc
publish_to: none
repository: https://github.com/alphamikle/nanc
homepage: https://nanc.io
version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  config:
    path: ../config
  model:
    path: ../model
  tools:
    path: ../tools
  fields:
    path: ../fields
  supabase_flutter: ^1.10.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  autoequal: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
    path: ../lint
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2
  build_runner: ^2.4.4
  autoequal_gen: ^0.5.1